In [2]:
import numpy as np

In [5]:
import pandas as pd

In [7]:
data_list = [1,2,3]

In [9]:
arr = np.array(data_list)

In [10]:
arr

array([1, 2, 3])

In [11]:
data_list2 = [[10,20,30],[40,50,60],[70,80,90]]

In [12]:
arr2 = np.array(data_list2)

In [13]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
arr3 = np.array([1,2,3,4,5])

In [15]:
arr3

array([1, 2, 3, 4, 5])

In [16]:
arr3[0]

1

In [17]:
arr3[4]

5

In [18]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [19]:
arr2[2,2]

90

In [20]:
arr2[0,0]

10

In [21]:
arr2[0,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [22]:
arr2[0,2]

30

In [23]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [27]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [28]:
np.arange(0,100,-1)

array([], dtype=int32)

In [44]:
print(*range(0,100,-1))

In [45]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [48]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [53]:
np.linspace(0,100,25)

array([  0.        ,   4.16666667,   8.33333333,  12.5       ,
        16.66666667,  20.83333333,  25.        ,  29.16666667,
        33.33333333,  37.5       ,  41.66666667,  45.83333333,
        50.        ,  54.16666667,  58.33333333,  62.5       ,
        66.66666667,  70.83333333,  75.        ,  79.16666667,
        83.33333333,  87.5       ,  91.66666667,  95.83333333,
       100.        ])

In [54]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [55]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [56]:
np.random.randint(0,10)

5

In [57]:
np.random.randint(0,10)

2

In [58]:
np.random.randint(15)

14

In [59]:
np.random.randint(15)

13

In [60]:
np.random.randint(15)

0

In [61]:
np.random.randint(1,10,5)

array([9, 3, 3, 1, 3])

In [63]:
np.random.rand(5)#0 ile 1 arasında rastgele 5 değer

array([0.55906305, 0.58529748, 0.35530661, 0.55835019, 0.4472565 ])

In [66]:
np.random.randn(5)#0 ın etrafında gaussian distrubiton? (-ler de çıkıyor)

array([-0.62639083, -0.29265562, -0.71710809,  0.64205499,  1.1407782 ])

In [67]:
arr = np.arange(25)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
arr.reshape(4,5)

ValueError: cannot reshape array of size 25 into shape (4,5)

In [71]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [72]:
newArray = np.random.randint(1,100,10)

In [73]:
newArray

array([57, 57, 90, 15, 52, 94, 69,  9, 62, 25])

In [74]:
newArray.max()

94

In [75]:
newArray.min()

9

In [76]:
newArray.sum()

530

In [78]:
newArray.mean()#ortalama

53.0

In [80]:
newArray.argmax()#max sayının olduğu index

5

In [81]:
newArray.argmin()

7

In [82]:
detArray = np.random.randint(1,100,25)

In [83]:
detArray

array([57, 64, 20, 61, 10,  8, 21, 31, 42, 77, 98,  4, 30, 29, 74, 75, 92,
       65, 70, 45, 97, 10, 81, 53, 47])

In [84]:
detArray = detArray.reshape(5,5)

In [85]:
detArray

array([[57, 64, 20, 61, 10],
       [ 8, 21, 31, 42, 77],
       [98,  4, 30, 29, 74],
       [75, 92, 65, 70, 45],
       [97, 10, 81, 53, 47]])

In [86]:
np.linalg.det(detArray)#determinant

1129962445.9999983

In [87]:
detArray2 = np.array([[1,2],[3,4]])

In [88]:
detArray2

array([[1, 2],
       [3, 4]])

In [89]:
np.linalg.det(detArray2)

-2.0000000000000004

In [90]:
round(np.linalg.det(detArray2))

-2

In [10]:
np.random.randint(1,4.8)

2

In [14]:
np.random.choose(5,10)

AttributeError: module 'numpy.random' has no attribute 'choose'

In [13]:
np.random.float(5,10)

AttributeError: module 'numpy.random' has no attribute 'float'