In [1]:
import numpy as np

In [4]:
arr = np.arange(1,10)

In [5]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[1]

2

In [7]:
arr[3]

4

In [9]:
arr[1:5]

array([2, 3, 4, 5])

In [10]:
arr[:4]

array([1, 2, 3, 4])

In [11]:
arr[::2]

array([1, 3, 5, 7, 9])

In [12]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [13]:
#listelerin aynısı

In [14]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[:3]

array([1, 2, 3])

In [16]:
arr[:3] = 25

In [17]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [18]:
arr[:3] = 6,6,6

In [19]:
arr

array([6, 6, 6, 4, 5, 6, 7, 8, 9])

In [20]:
arr = np.arange(1,10)

In [21]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr2 = arr

In [23]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr2[:3] = 100

In [25]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [27]:
arr#ikisi de değişir oluşturduğun arrayi değiştirdiği için iki değişken de değişiyor

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [29]:
arr = np.arange(1,10)

In [30]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr2 = arr.copy()

In [32]:
arr[:3] = 25

In [33]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [34]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr2[:3] = 100

In [36]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [37]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [39]:
newArray = np.arange(1,21)

In [40]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
newArray.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [42]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
newArray = newArray.reshape(5,4)

In [44]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [49]:
newArray[0,0]

1

In [50]:
newArray[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [51]:
newArray[:3,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [52]:
newArray[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
newArray[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
newArray[,:2]

SyntaxError: invalid syntax (Temp/ipykernel_9980/609629664.py, line 1)

In [57]:
arr = np.arange(1,11)

In [58]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [60]:
booleanArray = arr > 3

In [63]:
arr[booleanArray]#trueları bulduk...

array([ 4,  5,  6,  7,  8,  9, 10])

In [65]:
arr[arr>5]#trueları bulduk....

array([ 6,  7,  8,  9, 10])