In [1]:
import numpy as np

In [2]:
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([2,3,4,5,6,7])

In [3]:
arr1 + arr2

array([12, 23, 34, 45, 56, 67])

In [4]:
arr1*2

array([ 20,  40,  60,  80, 100, 120])

In [5]:
arr1/2

array([ 5., 10., 15., 20., 25., 30.])

In [6]:
arr1+np.arange(1,6)#boyutları farklı ondan toplanmıyo

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [7]:
arr1*arr2

array([ 20,  60, 120, 200, 300, 420])

In [8]:
arr1-arr2

array([ 8, 17, 26, 35, 44, 53])

In [9]:
arr1

array([10, 20, 30, 40, 50, 60])

In [10]:
arr1+10

array([20, 30, 40, 50, 60, 70])

In [11]:
arr2

array([2, 3, 4, 5, 6, 7])

In [12]:
arr2-2

array([0, 1, 2, 3, 4, 5])

In [13]:
arr1

array([10, 20, 30, 40, 50, 60])

In [15]:
np.sqrt(arr1)#karekök

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])

In [18]:
#numpy documentation (google)-> docs.scipy.org/doc/

In [19]:
#numpy seed (google)-> scipy.org