In [1]:
import numpy as np

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [9]:
arr = np.array([1,1,1,1,1])*10

In [10]:
arr

array([10, 10, 10, 10, 10])

In [12]:
(np.arange(1,17)).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
np.random.rand() * 5

3.645649351649278

In [19]:
np.random.randn(25).reshape(5,5)

array([[ 0.05401691,  1.5149463 ,  2.68138291, -1.51700926,  0.28196211],
       [ 0.16947642,  0.32812762, -0.18980199, -0.76010213,  0.64456496],
       [ 0.33416558, -0.21576912, -0.47247099,  1.46144238,  0.03189195],
       [-0.91258088, -0.12620163, -1.06564242,  1.07495846,  0.72773022],
       [-1.60688488,  0.10710154, -0.18799567,  0.0464384 , -0.52305577]])

In [21]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

ARRAY İNDEKSLENMESİ

In [22]:
arr  = np.arange(1,101).reshape(10,10)

In [23]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [25]:
arr[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [26]:
arr[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [31]:
arr[0:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [34]:
arr[0:3,1:2].reshape(1,3)

array([[ 2, 12, 22]])

In [35]:
arr[0:3,1:2]

array([[ 2],
       [12],
       [22]])

In [37]:
arr[:,9:].reshape(1,10)

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

OPERASYONLAR

In [53]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)#inte çevirip düzenliyor
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [54]:
arr1

array([[4, 1, 3],
       [3, 3, 0],
       [3, 0, 4]])

In [55]:
arr2

array([[2, 1, 1],
       [0, 0, 1],
       [1, 2, 1]])

In [56]:
arr1 = (np.random.rand(9) * 5)#0 ile 5 arasında 9 değer

In [57]:
arr1

array([2.29385063, 2.2148698 , 4.75722329, 3.72503415, 0.13222267,
       3.90283146, 0.24566488, 1.75930332, 0.13080189])

In [58]:
arr1 = (np.random.rand(9) * 10)#0 ile 10 arasında 9 değer

In [59]:
arr1

array([7.31772336, 8.81259243, 1.88682061, 7.72979648, 7.29659422,
       0.79976922, 8.37066276, 5.21093385, 5.79306394])

In [60]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [62]:
arr1

array([[0, 3, 3],
       [1, 4, 3],
       [1, 2, 2]])

In [63]:
arr2

array([[4, 1, 4],
       [4, 0, 2],
       [2, 4, 1]])

In [61]:
arr1+arr2

array([[4, 4, 7],
       [5, 4, 5],
       [3, 6, 3]])

In [64]:
arr1*arr2

array([[ 0,  3, 12],
       [ 4,  0,  6],
       [ 2,  8,  2]])

In [65]:
arr1.mean()

2.111111111111111

In [66]:
arr1.sum()

19

In [67]:
19/9

2.111111111111111

In [68]:
round(arr1.mean())

2